"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations = {
  en: {
    // Header
    lobby: 'Lobby',
    leaderboard: 'Leaderboard',
    history: 'History',
    search_room: 'Search Room ID',
    how_to_play: 'How to Play',
    how_to_play_title: 'TACTICAL MANUAL',
    how_to_play_desc: 'Learn the fundamentals of naval combat and master the battlefield.',
    how_to_play_video: 'Tutorial Video',
    
    // Detailed Manual
    manual_overview_title: 'Game Overview',
    manual_overview_desc: 'Battleship is a strategic 2-player naval combat simulation where commanders attempt to locate and eliminate the enemy fleet before their own is compromised.',
    manual_components_title: 'Operational Assets',
    manual_ocean_grid: 'Ocean Grid: Tactical deployment of your own fleet.',
    manual_target_grid: 'Target Grid: Intelligence gathering on enemy positions.',
    manual_peg_red: 'Red Hub: Confirmed hit on enemy vessel.',
    manual_peg_white: 'White Hub: Projectile miss, water impact.',
    
    manual_fleet_title: 'Fleet Composition',
    manual_fleet_desc: 'Every commander manages 5 specialized vessels with varying tactical signatures:',
    manual_ship_carrier: 'Carrier',
    manual_ship_battleship: 'Battleship',
    manual_ship_cruiser: 'Cruiser',
    manual_ship_submarine: 'Submarine',
    manual_ship_destroyer: 'Destroyer',
    ship_carrier: 'Carrier',
    ship_battleship: 'Battleship',
    ship_cruiser: 'Cruiser',
    ship_submarine: 'Submarine',
    ship_destroyer: 'Destroyer',
    
    manual_placement_title: 'Tactical Deployment Phase',
    manual_placement_desc: 'Before engagement, commanders must secretly position their units within the sector.',
    manual_placement_rules_title: 'Deployment Protocols:',
    manual_rule_1: 'Deployment limited to horizontal and vertical axis.',
    manual_rule_2: 'Diagonal orientation prohibited.',
    manual_rule_3: 'Units must remain within tactical grid boundaries.',
    manual_rule_4: 'Hull overlap is strictly prohibited.',
    manual_rule_5: 'Proximity deployment permitted.',
    manual_rule_6: 'Positioning is permanent once mission initiates.',
    
    manual_gameplay_title: 'Combat Engagement',
    manual_gameplay_desc: 'Commanders fire salvos by calling individual tactical coordinates (e.g., A5, C7).',
    manual_turn_process: 'Turn Protocol: Choose target -> Observe impact -> Update intelligence.',
    
    manual_sinking_title: 'Unit Elimination',
    manual_sinking_desc: 'When all modular sectors of a vessel are compromised, the unit is declared neutralized. Tradition dictates the signal: "You sank my battleship!"',
    
    manual_victory_title: 'Victory Condition',
    manual_victory_desc: 'Eliminate all 5 hostile units in the sector to achieve total victory.',
    
    step_1: 'PHASE 1: FLEET DEPLOYMENT',
    step_1_desc: 'Deploy your vessels across the 10x10 tactical grid. Ensure strategic positioning to minimize detection.',
    step_2: 'PHASE 2: TARGET ACQUISITION',
    step_2_desc: 'Engage enemy sectors. One shot per turn. Direct hits allow for consecutive strikes.',
    step_3: 'PHASE 3: TOTAL ELIMINATION',
    step_3_desc: 'Neutralize all units in the enemy fleet to achieve mission victory.',
    
    // Lobby
    deployment_zone: 'DEPLOYMENT ZONE',
    deployment_desc: 'Select a tactical operation or deploy immediately to the front lines.',
    quick_play: 'PvP Online',
    ranked_match: 'Global Matchmaking',
    pve_training: 'Ghost AI (PvE)',
    ready_to_deploy: 'READY TO DEPLOY',
    create_room: 'Create Custom Room',
    active_ops: 'Active Operations',
    op_name: 'Operation Name',
    difficulty: 'Difficulty',
    grid_size: 'Grid Size',
    captains: 'Captains',
    status: 'Status',
    deploy: 'JOIN',
    join: 'JOIN',
    action: 'ACTION',
    game_mode: 'Mode',
    mode_classic: 'CLASSIC',
    mode_salvo: 'SALVO',
    coming_soon: 'Coming Soon',
    top_commanders: 'Top Commanders',
    community_chat: 'Community Chat',
    broadcast: 'Broadcast message...',
    enter_callsign: 'Enter Callsign',
    identify_commander: 'Identify yourself, Commander.',
    placeholder_name: 'Enter your name...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    room_waiting: 'WAITING',
    room_placing: 'PREPARING',
    room_battle: 'BATTLE',
    room_full: 'FULL',
    opponent_left_title: 'OPPONENT DISCONNECTED',
    opponent_left_desc: 'The match has ended.',
    exit_to_lobby: 'BACK TO LOBBY',
    confirm_exit_room: 'Are you sure you want to abandon this operation?',
    abort_title: 'ABORT MISSION?',
    abort_description: 'You are about to withdraw from the current sector. All progress and tactical data will be lost. Admiral, confirm your orders.',
    keep_fighting: 'NEGATIVE, KEEP FIGHTING',
    confirm_abort: 'CONFIRM ABORT',
    
    // Placement
    unit_deployment: 'UNIT DEPLOYMENT',
    vessel_manifest: 'Vessel Manifest',
    init_fleet: 'Initialize Fleet',
    tactical_tools: 'Tactical Tools',
    rotate_ship: 'Rotate Ship',
    rotate_desc: 'Toggle orientation (Hotkey: R)',
    auto_deploy: 'Auto-Deploy',
    auto_desc: 'Randomize fleet deployment',
    reset_board: 'Reset Board',
    reset_desc: 'Clear all tactical active units',
    finding_opponent: 'FINDING OPPONENT...',
    units_missing: 'Units missing for deployment',
    verified: 'Verified',
    incomplete: 'Incomplete',
    auth_level: 'Auth Level',
    status_label: 'Status',
    pvp_online: 'PvP Online',
    pve_ghost: 'Ghost AI (PBE)',
    fleet_pvp: 'Fleet-to-Fleet (PVP)',
    ghost_pve: 'Ghost Simulation (PVE)',
    selected_mode: 'Selected Mode:',
    drag_drop_active: 'DRAG & DROP DEACTIVATED',
    commander_lbl: 'COMMANDER',
    sector_lbl: 'Sector 7-A',
    dock_auth_active: 'Dry Dock Authorization Active',
    server_online: 'Connected',
    server_offline: 'CONNECTING...',
    
    // Additional Placement strings
    score: 'SCORE',
    simulation_mode: 'Simulation Mode',
    live_combat: 'Live Combat',
    status_training: 'TRAINING',
    status_ready: 'READY',
    status_waiting: 'WAITING',
    abort_action: 'Abort',
    opponent_placing: 'OPPONENT IS PLACING SHIPS',
    searching_opponent: 'SEARCHING FOR OPPONENT...',
    come_to_battle: 'Come To Battle',
    units_placed_lbl: 'Units Placed',
    registry: 'REG',
    length: 'LEN',
    targeting_matrix: 'Targeting Matrix',
    scanning: 'Scanning...',
    placement_notes_title: 'Operation Notes',
    placement_instructions: 'Operator Manual',
    instruction_1: 'Select a ship from the manifest to deploy.',
    instruction_2: 'Left-click on the grid to place the ship.',
    instruction_3: 'Press \'R\' to change orientation.',
    instruction_4: 'You can Clear Fleet or Auto-deploy for quick setup.',
    instruction_5: 'Deployment requires all 5 vessels to initiate.',
    
    // Battle
    battle_arena: 'BATTLE ARENA',
    enemy_waters: 'Enemy Waters',
    defensive_grid: 'Defensive Grid',
    command_orders: 'Command Orders',
    battle_log: 'Battle Intel Log',
    live_feed: 'Live Operational Feed',
    sectors_active: 'Sectors Active',
    scanning_signals: 'Scanning for signals...',
    server_down_msg: 'Lost connection to Command Center. Server is offline.',
    find_match: 'FIND MATCH',
    lost_connection: 'LOST CONNECTION',

    // New Battle UI
    total_shots: 'Total Shots',
    hits: 'Hits',
    misses: 'Misses',
    accuracy: 'Accuracy',
    enemy_ships: 'Enemy Ships',
    momentum: 'Momentum',
    advantage_you: 'Advantage: You',
    advantage_enemy: 'Advantage: Enemy',
    score_label: 'SCORE',
    commander: 'Commander',
    opponent: 'Opponent',
    ghost_ai: 'GHOST AI',
    your_turn: 'Your Turn',
    enemy_turn: 'Enemy Turn',
    timer: 'Timer',
    connection_status: 'Establishing Connection',
    scanning_freq: 'Scanning Frequency 142.85 MHz...',
    victory: 'VICTORY',
    defeat: 'DEFEAT',
    victory_desc: 'You have successfully eliminated the enemy fleet and secured the sector.',
    defeat_desc: 'Commander, our forces have been overwhelmed. We must regroup.',
    rematch_accept: 'Accept Rematch Request',
    waiting_opponent_rematch: 'Waiting for opponent...',
    rematch_btn: 'Rematch',
    redeploy_btn: 'Re-deploy',
    return_to_base: 'Return to Base',
    fleet_active: 'My Matrix',
    op_log: 'Operational Log',
    you_go_first: 'YOU GO FIRST',
    enemy_go_first: 'ENEMY GO FIRST',
    your_fleet_status: 'Your Fleet Status',
    enemy_fleet_status: 'Enemy Fleet Status',

    // Battle Logs
    log_auto_fire: 'COMMANDER INACTIVE. AUTO-FIRE INITIATED.',
    log_strike_authorized: 'STRIKE AUTHORIZED',
    log_victory: 'VICTORY! ENEMY FLEET NEUTRALIZED. SECTOR SECURED.',
    log_mission_complete: 'MISSION COMPLETE',
    log_defeat: 'DEFEAT declared. Fleet non-operational.',
    log_mission_failed: 'MISSION FAILED',
    log_retreat: 'DEFEAT. FLEET DESTROYED. RETREAT IMMEDIATELY.',
    log_confirmed_kill: 'CONFIRMED KILL. ENEMY SHIP DESTROYED.',
    log_target_neutralized: 'TARGET NEUTRALIZED',
    log_warning_sunk: 'WARNING! {name} HAS BEEN DESTROYED!',
    log_critical_damage: 'CRITICAL DAMAGE',
    log_enemy_fired: 'Enemy fired at {pos}',
    log_direct_hit: 'DIRECT HIT!',
    log_splash_miss: 'Splash... Miss.',
    log_you_fired: 'You fired at {pos}',
    log_target_eliminated: 'TARGET ELIMINATED!',
    log_water_impact: 'Water impact. Miss.',
    log_negative_impact: 'NEGATIVE IMPACT. ENEMY TURN STARTING.',
    log_switching_defense: 'SWITCHING TO DEFENSE',
    log_confirmed_neutralized: 'CONFIRMED: {name} HAS BEEN NEUTRALIZED.',
    log_target_destroyed: 'TARGET DESTROYED',

    // Team Lobby
    team_lobby: 'COMMAND CENTER',
    create_or_join_squad: 'CREATE OR JOIN A SQUAD',
    team_lobby_btn: 'Online (PVP)',
    multiplayer_desc: 'READY TO DEPLOY',
    pve_training_title: 'PvE TRAINING',
    squad_lobby: 'Searching for Enemy Fleet',
    assemble_commanders: 'Assemble your fleet commanders',
    abandon_mission: 'Abandon Mission',
    commander_you: 'Commander (You)',
    allied_commander: 'Allied Commander',
    scanning_frequencies: 'Scanning Frequencies',
    waiting_connection: 'Waiting for allied commander to establish connection...',
    protocol_status: 'Protocol Status',
    pre_match_init: 'Pre-Match Initialization',
    readiness_desc: 'Both commanders must confirm their readiness status over the uplink before deployment protocol can be initiated.',
    initiate_deployment: 'Initiate Deployment',
    confirm_ready: 'Confirm Ready',
    cancel_ready: 'Cancel Ready',
    mission_confirmed: 'MISSION CONFIRMED',
    waiting_confirmation: 'WAITING FOR CONFIRMATION...',
    connection_active: 'Connection Active',
    connection_syncing: 'Connection Syncing',
    syncing_connection: 'Syncing Connection...',

    // General UI
    establishing_uplink: 'Initializing Connection...',
    reconnecting_op_zone: 'Reconnecting to Operation Zone...',
    online_count: '{count} Online',
    enter_to_ship: 'Enter to ship',
    no_active_ops: 'No active operations detected. Be the first to deploy.',
    sectors_detected: '{count} Sectors Detected',
    fleet_scanning: 'Active Fleet Scanning...',
    battle_status: 'Battle Status',
    
    // Connection Loading
    connecting_server: 'CONNECTING TO COMMAND CENTER...',
    taking_longer: 'The link is responding slower than usual.',
    connection_status_wait: 'Establishing secure uplink... please stand by.',
    connection_status_retry: 'Signal interference detected. Attempting to bypass...',
    wait_more: 'Wait More',
    return_to_home: 'Abort & Return',
    wait_msg: 'You can wait a moment or try again later.',
    uplink_status: 'Establishing Uplink',
    come_back_later: 'Systems may take about 1 minute to initialize.',
    
    // Settings
    settings: 'Settings',
    settings_subtitle: 'Configure Battle Interface',
    settings_language: 'Language',
    battle_layout: 'Interface Layout',
    layout_tactical: 'Optimal Layout',
    layout_tactical_desc: 'Standard tactical view with focus on enemy data.',
    layout_parallel: 'Song Song Layout',
    layout_parallel_desc: 'Two equal-sized grids side-by-side.',
    settings_health_bar: 'Health Bar Style',
    settings_health_bar_desc: 'Visual style for ship vitality indicators.',
    health_modern: 'Modern',
    health_minimalist: 'Minimalist',
    future_updates: 'Future Updates',
    settings_audio_feedback: 'Audio & Tactical Feedback',
    apply_changes: 'Apply Settings',
    footer_quote: 'The sea is not for the hesitant.',
    settings_vibration: 'Screen Vibration',
    settings_vibration_desc: 'Screen shake effects on hits and impacts.',
    settings_sound: 'Sound Effects',
    settings_sound_desc: 'Battle sounds, sonar, and notifications.',
    settings_background: 'Background',
    bg_tactical_grid: 'Tactical Grid',
    bg_tactical_grid_desc: 'Standard milspec grid.',
    bg_radar_sweep: 'Radar Sweep',
    bg_radar_sweep_desc: 'Active sonar tracking.',
    bg_dark_ocean: 'Dark Ocean',
    bg_dark_ocean_desc: 'Deep sea gradient.',
    bg_tactical_lines: 'HUD Lines',
    bg_tactical_lines_desc: 'Heads-up tactical display.',
    
    // Auth
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    no_account: "Don't have an account?",
    has_account: 'Already have an account?',
    identifying_commander: 'Identifying Commander...',
    authenticating: 'Authenticating...',
    auth_success: 'Authentication Successful',
    logout_success: 'Logout Successful',
    auth_failed: 'Authentication Failed',
    invalid_credentials: 'Invalid username or password',
    user_exists: 'User already exists',
    welcome_back: 'Welcome back, Admiral {name}',
    account_created: 'Account created successfully',
    login_required: 'Authorization Required',
    login_to_chat: 'Log in to participate in terminal communications',
    login_to_history: 'Log in to record match history and achievements',
    feature_restricted: 'This feature is restricted to registered Commanders only.',
    guest_commander: 'Temporary Commander',
    admiral: 'Admiral',
    opponent_title: 'Opponent',
    profile: 'Profile',
    friends: 'Friends',
    battle_history: 'Battle History',
    feedback: 'Feedback & Suggestions',
    feedback_subtitle: 'Help us improve the Battle Interface and Game Experience',
    feedback_category: 'Category',
    category_bug: 'Bug Report',
    category_feature: 'Feature Suggestion',
    category_other: 'Other',
    feedback_description: 'Detailed Description',
    feedback_placeholder: 'Describe your suggestions or report a bug...',
    send_feedback: 'Transmit Feedback',
    feedback_success: 'Feedback transmitted successfully! Thank you, Commander.',
    contact_info: 'Technical Support & Community',
    github_repo: 'Source Code / GitHub',
    donate: 'Support Development',
    donate_desc: 'Help keep the servers running and the fleet operational.',
    email_support: 'Email Support',
    hall_of_valor: 'Hall of Valor',
  },
  vi: {
    // Header
    lobby: 'Sảnh Chờ',
    leaderboard: 'Bảng Xếp Hạng',
    history: 'Lịch Sử',
    search_room: 'Tìm ID Phòng',
    how_to_play: 'Cách Chơi',
    how_to_play_title: 'CẨM NANG CHIẾN THUẬT',
    how_to_play_desc: 'Nắm vững các nguyên tắc hải chiến và làm chủ chiến trường.',
    how_to_play_video: 'Video Hướng Dẫn',
    
    // Detailed Manual
    manual_overview_title: 'Tổng Quan',
    manual_overview_desc: 'Battleship là trò chơi mô phỏng hải chiến chiến lược 2 người, nơi các chỉ huy cố gắng định vị và tiêu diệt hạm đội địch trước khi bị đánh bại.',
    manual_components_title: 'Khí Tài Tác Chiến',
    manual_ocean_grid: 'Lưới Đại Dương: Triển khai chiến thuật hạm đội của bạn.',
    manual_target_grid: 'Lưới Mục Tiêu: Thu thập thông tin tình báo về vị trí địch.',
    manual_peg_red: 'Chốt Đỏ: Xác nhận trúng tàu địch.',
    manual_peg_white: 'Chốt Trắng: Đạn trượt, rơi xuống nước.',
    
    manual_fleet_title: 'Cơ Cấu Hạm Đội',
    manual_fleet_desc: 'Mỗi chỉ huy quản lý 5 tàu chuyên dụng với các đặc điểm chiến thuật khác nhau:',
    manual_ship_carrier: 'Hàng Không Mẫu Hạm',
    manual_ship_battleship: 'Thiết Giáp Hạm',
    manual_ship_cruiser: 'Tuần Dương Hạm',
    manual_ship_submarine: 'Tàu Ngầm',
    manual_ship_destroyer: 'Khu Trục Hạm',
    ship_carrier: 'Mẫu Hạm',
    ship_battleship: 'Thiết Giáp',
    ship_cruiser: 'Tuần Dương',
    ship_submarine: 'Tàu Ngầm',
    ship_destroyer: 'Khu Trục',
    
    manual_placement_title: 'Giai Đoạn Triển Khai',
    manual_placement_desc: 'Trước khi giao tranh, các chỉ huy phải bí mật bố trí đơn vị trong khu vực.',
    manual_placement_rules_title: 'Giao Thức Triển Khai:',
    manual_rule_1: 'Triển khai giới hạn theo trục ngang và dọc.',
    manual_rule_2: 'Cấm bố trí theo đường chéo.',
    manual_rule_3: 'Đơn vị phải nằm trong ranh giới lưới chiến thuật.',
    manual_rule_4: 'Nghiêm cấm chồng chéo thân tàu.',
    manual_rule_5: 'Cho phép triển khai sát cạnh nhau.',
    manual_rule_6: 'Vị trí là cố định khi nhiệm vụ bắt đầu.',
    
    manual_gameplay_title: 'Giao Tranh',
    manual_gameplay_desc: 'Chỉ huy khai hỏa bằng cách gọi tọa độ chiến thuật (ví dụ: A5, C7).',
    manual_turn_process: 'Quy Trình Lượt: Chọn mục tiêu -> Quan sát tác động -> Cập nhật tình báo.',
    
    manual_sinking_title: 'Loại Bỏ Đơn Vị',
    manual_sinking_desc: 'Khi tất cả các phần của tàu bị bắn trúng, đơn vị được coi là bị vô hiệu hóa. Truyền thống quy định tín hiệu: "Ngươi đã đánh chìm tàu chiến của ta!"',
    
    manual_victory_title: 'Điều Kiện Thắng',
    manual_victory_desc: 'Tiêu diệt tất cả 5 đơn vị địch trong khu vực để giành chiến thắng toàn diện.',
    
    step_1: 'GIAI ĐOẠN 1: TRIỂN KHAI',
    step_1_desc: 'Bố trí tàu của bạn trên lưới chiến thuật 10x10. Đảm bảo vị trí chiến lược để giảm thiểu khả năng bị phát hiện.',
    step_2: 'GIAI ĐOẠN 2: XÁC ĐỊNH MỤC TIÊU',
    step_2_desc: 'Tấn công khu vực địch. Một phát bắn mỗi lượt. Bắn trúng cho phép tấn công liên tiếp (tùy luật chơi).',
    step_3: 'GIAI ĐOẠN 3: TIÊU DIỆT HOÀN TOÀN',
    step_3_desc: 'Vô hiệu hóa tất cả các đơn vị trong hạm đội địch để hoàn thành nhiệm vụ.',
    
    // Lobby
    deployment_zone: 'KHU VỰC TRIỂN KHAI',
    deployment_desc: 'Chọn một hoạt động chiến thuật hoặc triển khai ngay tới tiền tuyến.',
    quick_play: 'PvP Trực Tuyến',
    ranked_match: 'Ghép Trận Toàn Cầu',
    pve_training: 'Đấu Với Máy (PvE)',
    ready_to_deploy: 'SẴN SÀNG TRIỂN KHAI',
    create_room: 'Tạo Phòng Tùy Chỉnh',
    active_ops: 'Chiến Dịch Đang Hoạt Động',
    op_name: 'Tên Chiến Dịch',
    difficulty: 'Độ Khó',
    grid_size: 'Kích Thước Lưới',
    captains: 'Chỉ Huy',
    status: 'Trạng Thái',
    deploy: 'THAM GIA',
    join: 'THAM GIA',
    action: 'HÀNH ĐỘNG',
    game_mode: 'Chế Độ',
    mode_classic: 'CỔ ĐIỂN',
    mode_salvo: 'LOẠT ĐẠN',
    coming_soon: 'Sắp Ra Mắt',
    top_commanders: 'Chỉ Huy Hàng Đầu',
    community_chat: 'Kênh Cộng Đồng',
    broadcast: 'Gửi tin nhắn toàn kênh...',
    enter_callsign: 'Nhập Danh Hiệu',
    identify_commander: 'Xưng danh, thưa Chỉ huy.',
    placeholder_name: 'Nhập tên của bạn...',
    cancel: 'Hủy',
    confirm: 'Xác Nhận',
    room_waiting: 'ĐANG CHỜ',
    room_placing: 'CHUẨN BỊ',
    room_battle: 'CHIẾN ĐẤU',
    room_full: 'ĐẦY',
    opponent_left_title: 'ĐỐI THỦ NGẮT KẾT NỐI',
    opponent_left_desc: 'Trận đấu đã kết thúc.',
    exit_to_lobby: 'VỀ SẢNH CHỜ',
    confirm_exit_room: 'Bạn có chắc chắn muốn rời bỏ chiến dịch này?',
    abort_title: 'HỦY BỎ NHIỆM VỤ?',
    abort_description: 'Bạn sắp rút khỏi khu vực hiện tại. Mọi tiến trình và dữ liệu chiến thuật sẽ bị mất. Đô đốc, hãy xác nhận mệnh lệnh.',
    keep_fighting: 'TỪ CHỐI, TIẾP TỤC CHIẾN ĐẤU',
    confirm_abort: 'XÁC NHẬN RÚT LUI',
    
    // Placement
    unit_deployment: 'TRIỂN KHAI ĐƠN VỊ',
    vessel_manifest: 'Danh Mục Hạm Đội',
    init_fleet: 'Khởi Tạo Hạm Đội',
    tactical_tools: 'Công Cụ Chiến Thuật',
    rotate_ship: 'Xoay Tàu',
    rotate_desc: 'Đổi hướng (Phím tắt: R)',
    auto_deploy: 'Tự Động Đặt',
    auto_desc: 'Bố trí ngẫu nhiên',
    reset_board: 'Xóa Bàn',
    reset_desc: 'Gỡ bỏ mọi đơn vị',
    finding_opponent: 'ĐANG TÌM ĐỐI THỦ...',
    units_missing: 'Chưa đủ đơn vị để triển khai',
    verified: 'Đã Kiểm Tra',
    incomplete: 'Chưa Hoàn Tất',
    auth_level: 'Cấp Quyền',
    status_label: 'Trạng Thái',
    pvp_online: 'PvP Trực Tuyến',
    pve_ghost: 'Ghost AI (PBE)',
    fleet_pvp: 'Hạm Đội Chiến (PVP)',
    ghost_pve: 'Mô Phỏng Ghost (PVE)',
    selected_mode: 'Chế Độ Đã Chọn:',
    drag_drop_active: 'KÉO & THẢ ĐÃ TẮT',
    commander_lbl: 'CHỈ HUY',
    sector_lbl: 'Khu Vực 7-A',
    dock_auth_active: 'Đã Cấp Quyền Xưởng Tàu',
    server_online: 'Đã Kết Nối',
    server_offline: 'ĐANG KẾT NỐI...',
    
    // Additional Placement strings
    score: 'ĐIỂM',
    simulation_mode: 'Chế Độ Mô Phỏng',
    live_combat: 'Thực Chiến',
    status_training: 'HUẤN LUYỆN',
    status_ready: 'SẴN SÀNG',
    status_waiting: 'ĐANG CHỜ',
    abort_action: 'Hủy Bỏ',
    opponent_placing: 'ĐỐI THỦ ĐANG DÀN TRẬN',
    searching_opponent: 'ĐANG TÌM ĐỐI THỦ...',
    come_to_battle: 'ĐẾN CHIẾN TRƯỜNG',
    units_placed_lbl: 'Đơn Vị Đã Đặt',
    registry: 'MS',
    length: 'DÀI',
    targeting_matrix: 'Ma Trận Mục Tiêu',
    scanning: 'Đang Quét...',
    placement_notes_title: 'Ghi chú & Hướng dẫn',
    placement_instructions: 'Hướng dẫn vận hành',
    instruction_1: 'Chọn một tàu từ danh sách để bắt đầu đặt.',
    instruction_2: 'Nhấn chuột trái vào lưới để đặt tàu.',
    instruction_3: 'Phím \'R\' hoặc công cụ Xoay để đổi chiều.',
    instruction_4: 'Có thể Xóa đội tàu hoặc Tự động xếp nhanh.',
    instruction_5: 'Chỉ có thể bắt đầu khi xếp đủ 5 tàu.',
    
    // Battle
    battle_arena: 'CHIẾN TRƯỜNG',
    enemy_waters: 'Vùng Biển Địch',
    defensive_grid: 'Ma trận của bạn',
    command_orders: 'Mệnh Lệnh Chỉ Huy',
    battle_log: 'Nhật Ký Tác Chiến',
    live_feed: 'RADAR HOẠT ĐỘNG',
    sectors_active: 'KHU VỰC CÓ TÍN HIỆU',
    scanning_signals: 'Đang quét tín hiệu...',
    server_down_msg: 'Mất kết nối với trung tâm chỉ huy. Server sập rồi mấy ní ơi:))',
    find_match: 'TÌM TRẬN',
    lost_connection: 'MẤT KẾT NỐI',

    // New Battle UI
    total_shots: 'Tổng số lượt bắn',
    hits: 'Trúng đích',
    misses: 'Trượt',
    accuracy: 'Độ Chính Xác',
    enemy_ships: 'Tàu Địch',
    momentum: 'Thế Trận',
    advantage_you: 'Ưu Thế: Bạn',
    advantage_enemy: 'Ưu Thế: Địch',
    score_label: 'ĐIỂM',
    commander: 'Đô Đốc',
    opponent: 'Đối Thủ',
    ghost_ai: 'GHOST AI',
    your_turn: 'Lượt Của Bạn',
    enemy_turn: 'Lượt Kẻ Địch',
    timer: 'Thời Gian',
    connection_status: 'Đang Thiết Lập Kết Nối',
    scanning_freq: 'Đang Quét Tần Số 142.85 MHz...',
    victory: 'CHIẾN THẮNG',
    defeat: 'THẤT BẠI',
    victory_desc: 'Bạn đã tiêu diệt hoàn toàn hạm đội địch và làm chủ khu vực.',
    defeat_desc: 'Thưa Đô đốc, lực lượng của chúng ta đã bị áp đảo. Chúng ta cần tập hợp lại.',
    rematch_accept: 'Đồng ý yêu cầu chơi lại',
    waiting_opponent_rematch: 'Đang đợi đối thủ...',
    rematch_btn: 'Chơi Lại',
    redeploy_btn: 'Tái Triển Khai',
    return_to_base: 'Trở Về Căn Cứ',
    fleet_active: 'Ma Trận Của Tôi',
    op_log: 'NHẬT KÝ TÁC CHIẾN',
    you_go_first: 'BẠN ĐI TRƯỚC',
    enemy_go_first: 'ĐỐI THỦ ĐI TRƯỚC',
    your_fleet_status: 'Trạng Thái Hạm Đội',
    enemy_fleet_status: 'Trạng Thái Địch',

    // Battle Logs
    log_auto_fire: 'CHỈ HUY KHÔNG PHẢN HỒI. TỰ ĐỘNG KHAI HỎA.',
    log_strike_authorized: 'LỆNH CÔNG KÍCH ĐÃ DUYỆT',
    log_victory: 'CHIẾN THẮNG! HẠM ĐỘI ĐỊCH ĐÃ BỊ LOẠI BỎ. KHU VỰC ĐÃ AN TOÀN.',
    log_mission_complete: 'CHIẾN DỊCH HOÀN TẤT',
    log_defeat: 'THẤT BẠI. Hạm đội không còn khả năng tác chiến.',
    log_mission_failed: 'CHIẾN DỊCH THẤT BẠI',
    log_retreat: 'THẤT BẠI. HẠM ĐỘI ĐÃ BỊ PHÁ HỦY. RÚT QUÂN NGAY LẬP TỨC.',
    log_confirmed_kill: 'XÁC NHẬN TIÊU DIỆT. TÀU ĐỊCH ĐÃ BỊ PHÁ HỦY.',
    log_target_neutralized: 'MỤC TIÊU ĐÃ BỊ LOẠI BỎ',
    log_warning_sunk: 'CẢNH BÁO! {name} ĐÃ BỊ PHÁ HỦY!',
    log_critical_damage: 'THIỆT HẠI NGHIÊM TRỌNG',
    log_enemy_fired: 'Địch khai hỏa tại {pos}',
    log_direct_hit: 'TRÚNG ĐÍCH!',
    log_splash_miss: 'Trượt... Chỉ trúng nước.',
    log_you_fired: 'Bạn khai hỏa tại {pos}',
    log_target_eliminated: 'MỤC TIÊU ĐÃ BỊ TIÊU DIỆT!',
    log_water_impact: 'Trúng nước. Trượt.',
    log_negative_impact: 'CÔNG KÍCH THẤT BẠI. LƯỢT CỦA ĐỊCH BẮT ĐẦU.',
    log_switching_defense: 'CHUYỂN SANG PHÒNG THỦ',
    log_confirmed_neutralized: 'XÁC NHẬN: {name} ĐÃ BỊ LOẠI BỎ.',
    log_target_destroyed: 'MỤC TIÊU ĐÃ BỊ PHÁ HỦY',

    // Team Lobby
    team_lobby: 'TRUNG TÂM CHỈ HUY',
    create_or_join_squad: 'TẠO HOẶC THAM GIA ĐỘI',
    team_lobby_btn: 'Trực tuyến (pvp)',
    multiplayer_desc: 'SẴN SÀNG XUẤT KÍCH',
    pve_training_title: 'HUẤN LUYỆN (pve)',
    squad_lobby: 'Đang dò hạm đội địch',
    assemble_commanders: 'Tập hợp các chỉ huy hạm đội của bạn',
    abandon_mission: 'Rời Bỏ Nhiệm Vụ',
    commander_you: 'Đô Đốc (Bạn)',
    allied_commander: 'Đồng Minh',
    scanning_frequencies: 'Đang Quét Tần Số',
    waiting_connection: 'Đang chờ đồng minh thiết lập kết nối...',
    protocol_status: 'Trạng Thái Giao Thức',
    pre_match_init: 'Khởi Tạo Trước Trận Đấu',
    readiness_desc: 'Cả hai chỉ huy phải xác nhận trạng thái sẵn sàng qua liên kết trước khi bắt đầu quy trình triển khai.',
    initiate_deployment: 'Bắt Đầu Triển Khai',
    confirm_ready: 'Xác Nhận Sẵn Sàng',
    cancel_ready: 'Hủy Sẵn Sàng',
    mission_confirmed: 'NHIỆM VỤ Đã XÁC NHẬN',
    waiting_confirmation: 'ĐANG CHỜ XÁC NHẬN...',
    connection_active: 'Kết Nối Hoạt Động',
    connection_syncing: 'Đang Đồng Bộ Kết Nối',
    syncing_connection: 'Đang Đồng Bộ Kết Nối...',

    // General UI
    establishing_uplink: 'Đang khởi tạo kết nối...',
    reconnecting_op_zone: 'Đang kết nối lại vùng tác chiến...',
    online_count: '{count} Trực Tuyến',
    enter_to_ship: 'Nhấn Enter để gửi',
    no_active_ops: 'Không tìm thấy chiến dịch nào. Hãy là người đầu tiên tham chiến.',
    sectors_detected: 'Phát hiện {count} Khu Vực',
    fleet_scanning: 'Đang quét hạm đội...',
    battle_status: 'CHIẾN TRẠNG',

    // Connection Loading
    connecting_server: 'ĐANG KẾT NỐI TỚI TRUNG TÂM CHỈ HUY...',
    taking_longer: 'Máy chủ phản hồi chậm hơn bình thường.',
    connection_status_wait: 'Đang thiết lập liên kết an toàn... vui lòng đợi.',
    connection_status_retry: 'TÍN HIỆU NHIỄU. ĐANG THỬ BỎ QUA...',
    wait_more: 'Tiếp tục chờ',
    return_to_home: 'Quay lại sảnh',
    wait_msg: 'Máy chủ đang được khởi động lại sau thời gian nghỉ ngơi Zzzzz.',
    uplink_status: 'ĐANG THIẾT LẬP LIÊN KẾT',
    come_back_later: 'Hệ thống có thể mất khoảng 1 phút để ổn định.',
    
    // Settings
    settings: 'Cài Đặt',
    settings_subtitle: 'Cấu Hình Giao Diện Tác Chiến',
    settings_language: 'Ngôn Ngữ',
    battle_layout: 'Bố Cục Giao Diện',
    layout_tactical: 'Bố Cục Tối Ưu',
    layout_tactical_desc: 'Chế độ chuẩn tập trung vào dữ liệu kẻ thù.',
    layout_parallel: 'Bố Cục Song Song',
    layout_parallel_desc: 'Hai lưới kích thước bằng nhau hiển thị song song.',
    settings_health_bar: 'Kiểu Thanh Máu',
    settings_health_bar_desc: 'Phong cách hiển thị tình trạng tàu.',
    health_modern: 'Hiện Đại',
    health_minimalist: 'Tối Giản',
    future_updates: 'Cập Nhật Tương Lai',
    settings_audio_feedback: 'Âm Thanh & Phản Hồi',
    apply_changes: 'Áp Dụng Thay Đổi',
    footer_quote: 'Biển không dành cho kẻ do dự.',
    settings_vibration: 'Rung Màn Hình',
    settings_vibration_desc: 'Hiệu ứng rung khi trúng đạn và va chạm.',
    settings_sound: 'Âm Thanh',
    settings_sound_desc: 'Tiếng súng, radar và thông báo tác chiến.',
    settings_background: 'Hình Nền',
    bg_tactical_grid: 'Lưới Chiến Thuật',
    bg_tactical_grid_desc: 'Lưới quân sự tiêu chuẩn.',
    bg_radar_sweep: 'Radar Quét',
    bg_radar_sweep_desc: 'Dò tìm sonar đang hoạt động.',
    bg_dark_ocean: 'Sóng Biển Đêm',
    bg_dark_ocean_desc: 'Đại dương xanh thẳm.',
    bg_tactical_lines: 'HUD Quân Sự',
    bg_tactical_lines_desc: 'Giao diện mục tiêu quân sự.',

    // Auth
    login: 'Đăng Nhập',
    register: 'Đăng Ký',
    logout: 'Đăng Xuất',
    username: 'Tên Đô Đốc',
    email: 'Email Hệ Thống',
    password: 'Mật Mã',
    confirm_password: 'Xác Nhận Mật Mã',
    no_account: 'Chưa có tài khoản?',
    has_account: 'Đã có tài khoản?',
    identifying_commander: 'Đang xác nhận danh tính...',
    authenticating: 'Đang xác thực...',
    auth_success: 'Xác thực thành công',
    logout_success: 'Đăng xuất thành công',
    auth_failed: 'Xác thực thất bại',
    invalid_credentials: 'Tên hoặc mật mã không chính xác',
    user_exists: 'Tài khoản đã tồn tại',
    welcome_back: 'Chào mừng trở lại, Đô đốc {name}',
    account_created: 'Tạo tài khoản thành công',
    login_required: 'Đăng Nhập Để Tham Gia',
    login_to_chat: 'Kết nối và trò chuyện cùng các Đô đốc khác.',
    login_to_history: 'Đăng nhập để lưu lịch sử đấu và thành tựu',
    feature_restricted: 'Tính năng này chỉ dành cho các Đô đốc đã đăng ký.',
    guest_commander: 'Chỉ Huy Tạm Thời',
    admiral: 'Đô Đốc',
    opponent_title: 'Đối Thủ',
    profile: 'Hồ Sơ',
    friends: 'Bạn Bè',
    battle_history: 'Lịch Sử Đấu',
    feedback: 'Góp Ý & Phản Hồi',
    feedback_subtitle: 'Giúp chúng tôi cải thiện giao diện và trải nghiệm trò chơi',
    feedback_category: 'Phân Loại',
    category_bug: 'Báo Cáo Lỗi',
    category_feature: 'Góp Ý Tính Năng',
    category_other: 'Yêu Cầu Khác',
    feedback_description: 'Mô Tả Chi Tiết',
    feedback_placeholder: 'Mô tả ý tưởng của bạn hoặc báo cáo lỗi gặp phải...',
    send_feedback: 'Gửi Phản Hồi',
    feedback_success: 'Đã gửi phản hồi thành công! Cảm ơn Đô đốc.',
    contact_info: 'Hỗ Trợ Kỹ Thuật & Cộng Đồng',
    github_repo: 'Mã Nguồn / GitHub',
    donate: 'Ủng Hộ Phát Triển',
    donate_desc: 'Giúp duy trì máy chủ và hạm đội hoạt động ổn định.',
    email_support: 'Liên Hệ Qua Email',
    hall_of_valor: 'BẢNG VÀNG VINH DANH',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Load language preference from local storage
  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language;
    if (saved && (saved === 'en' || saved === 'vi')) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string, params?: Record<string, string>) => {
    let translation = translations[language][key as keyof typeof translations['en']] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        translation = translation.replace(`{${k}}`, v);
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
